
USE ROLE sysadmin; 

-- SETUP DATABASE AND STAGING LAYER 
CREATE DATABASE IF NOT EXISTS job_ads; 

-- STAGING LAYER (SCHEMA) IS A LANDING ZONE WHERE DATA IS LOADDED 
CREATE SCHEMA IF NOT EXISTS job_ads.staging; 

SHOW DATABASES; 

DESCRIBE DATABASE job_ads; 