models:
  - name: dim_employer
    description: "Information about the employer such as name, workplace address, ogranisation number, ..."
    columns:
      - name: employer_id
        description: "Primary Key, a surrogate key generated based on columns: id, employer_name"
        data_tests:
          - unique
          - not_null

      - name: workplace_city
        data_tests:
          - not_null

  - name: dim_job_details
    columns:
      - name: job_details_id
        data_tests:
          - not_null
          - unique

      - name: headline
        data_tests:
          - not_null

  - name: fct_job_ads
    columns:
      - name: job_details_id
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_job_details')
                field: job_details_id
