
USE ROLE sysadmin; 

-- SETUP DATABASE AND STAGING LAYER 
CREATE DATABASE IF NOT EXISTS movies; 

-- STAGING LAYER (SCHEMA) IS A LANDING ZONE WHERE DATA IS LOADDED 
CREATE SCHEMA IF NOT EXISTS movies.staging; 

SHOW DATABASES; 

DESCRIBE DATABASE MOVIES; 


USE DATABASE movies; 

USE SCHEMA movies.staging; 

