-- USE ROLE USER ADMIN 
-- TO CREATE USER ROLES 
USE ROLE USERADMIN; 

--create three different roles 
CREATE ROLE ICE_CREAM_READER COMMENT = "able to read ice_cream_db";
CREATE ROLE ICE_CREAM_WRITER COMMENT = "able to do CRUD operations on ice_cream_db";
CREATE ROLE ICE_CREAM_ANALYST COMMENT = "able to create views on on ice_cream_db";

-- show the roles 
SHOW ROLES; 

-- MANGE SOM GRANTS 
USE ROLE SECURITYADMIN; 

-- GRANT USAGE ON WAREHOUSE TO THE ROLE
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE ICE_CREAM_READER; 
GRANT USAGE ON DATABASE ICE_CREAM_DB TO ROLE ICE_CREAM_READER; 
GRANT USAGE ON ALL SCHEMAS IN DATABASE ICE_CREAM_DB TO ROLE ICE_CREAM_READER; 


-- CRUD OPERATONS (READ)
-- PUBLIC SCHEMAM BY DEFAULT 

-- SELECT TO ICE CREAM READER 
GRANT SELECT ON ALL TABLES IN SCHEMA ICE_CREAM_DB.PUBLIC TO ICE_CREAM_READER;

-- GRANT FUTURE TABLES PREMISSION 
GRANT SELECT ON FUTURE TABLES IN SCHEMA ICE_CREAM_DB.PUBLIC TO ICE_CREAM_READER; 

SHOW GRANTS TO ROLE ICE_CREAM_READER; 


SHOW FUTURE GRANTS IN SCHEMA ICE_CREAM_DB.PUBLIC; 

-- GRANT ROLE TO ICE CREAM READER TO WRITER 
GRANT ROLE ICE_CREAM_READER TO ROLE ICE_CREAM_WRITER;

SHOW GRANTS TO ROLE ICE_CREAM_WRITER;

-- GRANT CRUD OPERATION TO ICE CREAM WRITER 
GRANT 
    INSERT, UPDATE, DELETE 
    ON ALL TABLES 
    IN SCHEMA ICE_CREAM_DB.PUBLIC TO ROLE ICE_CREAM_WRITER; 

-- FUTURE TABLES 
GRANT 
    INSERT, UPDATE, DELETE 
    ON FUTURE TABLES 
    IN SCHEMA ICE_CREAM_DB.PUBLIC TO ROLE ICE_CREAM_WRITER; 


GRANT CREATE TABLE ON SCHEMA ICE_CREAM_DB.PUBLIC TO ROLE ICE_CREAM_WRITER; 


SHOW GRANTS TO ROLE ICE_CREAM_WRITER; 

SHOW FUTURE GRANTS IN SCHEMA ICE_CREAM_DB.PUBLIC; 

USE ROLE USERADMIN; 


GRANT ROLE ICE_CREAM_WRITER TO USER mirandalyng; 



