
-- SYSADMIN is responsible for creating warehouse and databases
USE ROLE SYSADMIN;

-- function to run current role 
SELECT current_role(); 
-- see currenct user 
SELECT CURRENT_USER(); 
-- create database 
CREATE DATABASE IF NOT EXISTS ICE_CREAM_DB; 


-- CREATE TABLES  
CREATE TABLE IF NOT EXISTS FLAVORS (
    FLAVOR_ID INT PRIMARY KEY AUTOINCREMENT, 
    FLAVOR_NAME STRING, 
    PRICE DECIMAL(5,2)
); 

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY AUTOINCREMENT, 
    CUSTOMER_NAME STRING, 
    EMAIL STRING
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID INT PRIMARY KEY AUTOINCREMENT, 
    CUSTOMER_ID INT, 
    FLAVOR_ID INT, 
    QUANTITY INT, 
    TRANSACTION_DATE TIMESTAMP, 
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID), 
    FOREIGN KEY (FLAVOR_ID) REFERENCES FLAVORS (FLAVOR_ID)
);