USE ROLE SYSADMIN;

USE DATABASE JOB_ADS;

CREATE SCHEMA IF NOT EXISTS marts; 

SHOW SCHEMAS IN DATABASE JOB_ADS;

USE ROLE SECURITYADMIN; 


-- GRANT USAGE 
GRANT USAGE, 
CREATE TABLE, 
CREATE VIEW ON SCHEMA job_ads.marts TO ROLE JOB_ADS_DBT_ROLE; 

-- GRANT ON TABLES AND VIEWS 
GRANT SELECT, 
INSERT, 
UPDATE, 
DELETE ON ALL TABLES IN SCHEMA job_ads.marts TO ROLE job_ads_dbt_role; 

GRANT SELECT ON ALL VIEWS IN SCHEMA JOB_ADS.MARTS TO ROLE JOB_ADS_DBT_ROLE; 


-- FUTURE TABLES AND VIEWS 
GRANT SELECT, 
INSERT, 
UPDATE, 
DELETE ON FUTURE TABLES IN SCHEMA job_ads.marts TO ROLE job_ads_dbt_role; 

GRANT SELECT ON FUTURE VIEWS IN SCHEMA JOB_ADS.MARTS TO ROLE JOB_ADS_DBT_ROLE; 

USE ROLE JOB_ADS_DBT_ROLE; 

SHOW GRANTS ON SCHEMA JOB_ADS.MARTS; 


-- MANUAL TEST 
USE SCHEMA JOB_ADS.MARTS;

CREATE TABLE test (id INT);

SHOW TABLES; 


DROP TABLE TEST; 



